### PR TITLE
(possibly fatal) check for Rcpp and RcppArmadillo now opt-in (closes #19)

### LINKED ISSUE #19: Package usage error - RcppExports includes Rcpp and RcppArmadillo
Thank you for creating a great package that is easy to use. However, when creating a `R` package with `RcppEnsmallen` I am encountering an error that I'm not sure how to address. In the RcppExports.cpp file there are include statements for both `Rcpp` and `RcppArmadillo`, which is leading to the error "`Do not include either 'Rcpp.h' or 'RcppArmadillo.h'. Please only use 'RcppEnsmallen.h'`." Because the RcppExports.cpp file is generated by the `Rcpp::compileAttributes()` function I am not sure how to correct this. This is only an issue I've encountered when creating a package, not when running individual script files via `Rcpp::sourceCpp()`.

I am a beginner to using `Rcpp` so there might be something simple that I am missing. I use `devtools` and RStudio for creating packages, and from my understanding `devtools::document()`, as well as the RStudio package build/reload tools, automatically calls the `Rcpp::compileAttributes()` function. My .cpp file containing functions only begins with the following: 

```
#include <RcppEnsmallen.h>
#include <RcppArmadilloExtensions/sample.h>

// [[Rcpp::plugins("cpp11")]]

// [[Rcpp::depends(RcppEnsmallen)]]

using namespace Rcpp;

```
In my use of `RcppEnsmallen` by just calling `Rcpp::sourceCpp()` on scripts rather than developing a package, I do not encounter any errors. I'm not sure what is the proper way to address the RcppExports file however.

Any help would be greatly appreciated, I look forward to continue to use `RcppEnsmallen` in my research.

### PR DESCRIPTION
**Pull request by eddelbuettel**

### CODE REVIEW

**Comment by eddelbuettel** [comment]
See #19 for discussion and context.

**Comment by coatless** [comment]
@eddelbuettel I think we can just get rid of header check instead of providing a define. 

The logic here was present if we needed extra defines. However, Ensmallen is automatically using variables set inside RcppArmadillo (e.g. redirect of STDOUT/STDERR and RNG).

**Comment by eddelbuettel** [comment]
Either way it needs fixing. 

One way would be to merge PR and then refine, another to mod the PR then merge.

**Comment by coatless** [comment]
Done. Closes out #19

**Pull request merged**
